# Generated by Django 4.2.5 on 2023-09-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tedashcore', '0003_alter_report_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default="", max_length=300),
            preserve_default=False,
        ),
    ]
