# Generated by Django 4.2.5 on 2023-09-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tedashcore', '0004_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
