# Generated by Django 4.2.5 on 2023-10-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tedashcore', '0005_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.JSONField(),
        ),
    ]
