# Generated by Django 4.2.5 on 2023-10-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tedashcore", "0006_alter_report_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="kind",
            field=models.CharField(
                choices=[("JU", "JUnit")], default="JU", max_length=2
            ),
            preserve_default=False,
        ),
    ]
